[package]
name = "cgroups_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgroups-rs = "0.3.4"

[lib]
crate-type = ["staticlib"]
name = "cgroups_ffi"
